# ==========================================
# face_smiling.png
# ==========================================
:grinning:=\uF400
:smiley:=\uF401
:smile:=\uF402
:grin:=\uF403
:laughing:=\uF404
:sweat_smile:=\uF405
:rofl:=\uF406
:joy:=\uF407
:slight_smile:=\uF408
:upside_down:=\uF409
:wink:=\uF40A
:blush:=\uF40B
:innocent:=\uF40C

# ==========================================
# face_affection.png
# ==========================================
:smiling_face_with_3_hearts:=\uF40D
:heart_eyes:=\uF40E
:kissing_heart:=\uF40F
:relaxed:=\uF410
:kissing_closed_eyes:=\uF411
:smiling_face_with_tear:=\uF412

# ==========================================
# face_tongue.png
# ==========================================
:yum:=\uF413
:stuck_out_tongue:=\uF414
:stuck_out_tongue_winking_eye:=\uF415
:zany_face:=\uF416
:stuck_out_tongue_closed_eyes:=\uF417
:money_mouth:=\uF418

# ==========================================
# face_hand.png
# ==========================================
:hugging:=\uF419
:face_with_hand_over_mouth:=\uF41A
:gasp:=\uF41B
:face_with_peeking_eye:=\uF41C
:shushing_face:=\uF41D
:thinking:=\uF41E
:saluting_face:=\uF41F

# ==========================================
# face_neutral_skeptical.png
# ==========================================
:zipper_mouth:=\uF420
:face_with_raised_eyebrow:=\uF421
:neutral_face:=\uF422
:expressionless:=\uF423
:no_mouth:=\uF424
:dotted_line_face:=\uF425
:smirk:=\uF426
:unamused:=\uF427
:rolling_eyes:=\uF428
:grimacing:=\uF429
:lying_face:=\uF42A

# ==========================================
# face_sleepy.png
# ==========================================
:relieved:=\uF42B
:pensive:=\uF42C
:sleepy:=\uF42D
:drooling_face:=\uF42E
:sleeping:=\uF42F
:face_exhaling:=\uF430

# ==========================================
# face_unwell.png
# ==========================================
:face_vomiting:=\uF431
:sneezing_face:=\uF432
:hot_face:=\uF433
:cold_face:=\uF434
:woozy_face:=\uF435
:dizzy_face:=\uF436
:exploding_head:=\uF437

# ==========================================
# face_hat.png
# ==========================================
:partying_face:=\uF438

# ==========================================
# face_glasses.png
# ==========================================
:sunglasses:=\uF439
:nerd:=\uF43A
:face_with_monocle:=\uF43B

# ==========================================
# face_concerned.png
# ==========================================
:slight_frown:=\uF43C
:open_mouth:=\uF43D
:astonished:=\uF43E
:flushed:=\uF43F
:pleading_face:=\uF440
:face_holding_back_tears:=\uF441
:frowning:=\uF442
:anguished:=\uF443
:fearful:=\uF444
:cold_sweat:=\uF445
:disappointed_relieved:=\uF446
:cry:=\uF447
:sob:=\uF448
:scream:=\uF449
:persevere:=\uF44A
:sweat:=\uF44B
:tired_face:=\uF44C
:yawning_face:=\uF44D

# ==========================================
# face_negative.png
# ==========================================
:rage:=\uF44E
:angry:=\uF44F
:smiling_imp:=\uF450
:skull:=\uF451

# ==========================================
# face_costume.png
# ==========================================
:poop:=\uF452
:clown:=\uF453
:ghost:=\uF454
:alien:=\uF455

# ==========================================
# cat_face.png
# ==========================================
:smiley_cat:=\uF456
:smile_cat:=\uF457
:joy_cat:=\uF458
:heart_eyes_cat:=\uF459
:smirk_cat:=\uF45A
:kissing_cat:=\uF45B
:scream_cat:=\uF45C
:crying_cat_face:=\uF45D
:pouting_cat:=\uF45E

# ==========================================
# monkey_face.png
# ==========================================
:see_no_evil:=\uF45F
:hear_no_evil:=\uF460
:speak_no_evil:=\uF461

# ==========================================
# heart.png
# ==========================================
:sparkling_heart:=\uF462
:revolving_hearts:=\uF463
:broken_heart:=\uF464
:heart:=\uF465
:pink_heart:=\uF466
:blue_heart:=\uF467
:purple_heart:=\uF468
:white_heart:=\uF469

# ==========================================
# emotion.png
# ==========================================
:100:=\uF46A
:boom:=\uF46B
:sweat_drops:=\uF46C
:speech_balloon:=\uF46D
:zzz:=\uF46E

# ==========================================
# hand_fingers_open.png
# ==========================================
:wave:=\uF46F

# ==========================================
# hand_fingers_partial.png
# ==========================================
:ok_hand:=\uF470
:pinched_fingers:=\uF471
:pinching_hand:=\uF472
:v:=\uF473
:finger_heart:=\uF474
:call_me:=\uF475

# ==========================================
# hand_single_finger.png
# ==========================================
:point_left:=\uF476
:point_right:=\uF477
:point_up_2:=\uF478
:middle_finger:=\uF479
:point_down:=\uF47A
:point_up:=\uF47B

# ==========================================
# hand_fingers_closed.png
# ==========================================
:thumbsup:=\uF47C
:thumbsdown:=\uF47D
:fist:=\uF47E
:punch:=\uF47F
:left_facing_fist:=\uF480
:right_facing_fist:=\uF481

# ==========================================
# hands.png
# ==========================================
:clap:=\uF482
:raised_hands:=\uF483
:heart_hands:=\uF484
:open_hands:=\uF485
:palms_up_together:=\uF486
:handshake:=\uF487
:pray:=\uF488

# ==========================================
# body_parts.png
# ==========================================
:muscle:=\uF48C
:eyes:=\uF48D
:tongue:=\uF48E
:biting_lip:=\uF48F

# ==========================================
# plant_flower.png
# ==========================================
:wilted_rose:=\uF490

# ==========================================
# award_medal.png
# ==========================================
:trophy:=\uF491
:first_place:=\uF492
:second_place:=\uF493
:third_place:=\uF494

# ==========================================
# event.png
# ==========================================

# ==========================================
# heart_on_fire_mending_heart.png
# ==========================================
:heart_on_fire:=\uF497
:mending_heart:=\uF498

# ==========================================
# sky_weather.png
# ==========================================
:fire:=\uF4C5

# ==========================================
# troll.png
# ==========================================
:polite_stare:=\uF499
:verne_stare:=\uF49A
:smile2:=\uF49B
:valorsweat:=\uF49C
:clueless:=\uF49D
:brilliant:=\uF49E
:waving:=\uF49F
:aru:=\uF4A0
:drinking:=\uF4A1
:animethinking:=\uF4A2
:shrug2:=\uF4A3
:WOW:=\uF4A4
:hehe:=\uF4A5
:analysis:=\uF4A6
:steamsad:=\uF4A7
:steammocking:=\uF4A8
:steamtired:=\uF4A9
:hellskitchen:=\uF4AA
:steamhappy:=\uF4AB
:tired:=\uF4AC
:sprok:=\uF4AD
:reallysus:=\uF4AE
:beehappy:=\uF4AF
:bleh:=\uF4B0
:sillyaf:=\uF4B1
:smug:=\uF4B2
:nombread:=\uF4B3
:BAHAHA:=\uF4B4
:speed:=\uF4B5
:shy:=\uF4B6
:sus:=\uF4B7
:steamfacepalm:=\uF4B8
:soggycat:=\uF4B9
:copium:=\uF4BA
:clueless_dog:=\uF4BB
:caught:=\uF4BC
:hmph:=\uF4BD
:shocked:=\uF4BE
:idk:=\uF4BF
:thumbup:=\uF4C0

# ==========================================
# weepbob.png
# ==========================================
:weepbob:=\uF4C1
